# Generated by Django 3.2.6 on 2021-09-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('apiId', models.AutoField(primary_key=True, serialize=False)),
                ('apiName', models.CharField(max_length=25)),
                ('apiLink', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BLOG',
            fields=[
                ('blogId', models.AutoField(primary_key=True, serialize=False)),
                ('blogTitle', models.CharField(max_length=80)),
                ('blogCategory', models.CharField(blank=True, choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Coding', 'Coding'), ('Entertaintment', 'Entertaintment')], default='SELECT', max_length=150, null=True)),
                ('blogDesc', models.CharField(max_length=1500)),
                ('blogImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('blogDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NOTE',
            fields=[
                ('noteId', models.AutoField(primary_key=True, serialize=False)),
                ('noteTitle', models.CharField(max_length=50)),
                ('noteDesc', models.CharField(max_length=200)),
            ],
        ),
    ]
