# Generated by Django 3.2.6 on 2021-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_note_notedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='noteDesc',
            field=models.CharField(max_length=1000),
        ),
    ]
