# Generated by Django 3.2.6 on 2021-09-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_note_notedesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogDesc',
            field=models.CharField(max_length=10000),
        ),
    ]
