# Generated by Django 3.2.6 on 2021-09-04 11:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_blogdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogDesc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
