# Generated by Django 3.2.6 on 2021-09-04 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blog_blogdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogSummary',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
